version: "2"
services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: simonluijk/docker-postgres-dev:11.5
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/11
    ports:
      - 5432:5432
